version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
  sistemaDeVendas:
    depends_on:
      - "rabbitmq"
    ports: 
      - "8081:8080"
    build: ./sistemaDeVendas
    image: "sistemadevendas:latest"
  servEstoque:
    depends_on:
      - "rabbitmq"
      - "sistemaDeVendas"
    ports: 
      - "8082:8080"
    build: ./servEstoque
    image: "servestoque:latest"
  servVendas:
    depends_on:
      - "rabbitmq"
      - "sistemaDeVendas"
    ports: 
      - "8083:8080"
    build: ./servVendas
    image: "servvendas:latest"
  gateway:
    ports:
      - "8080:8080"
    depends_on:
      - "sistemaDeVendas"
      - "servEstoque"
      - "servVendas"
    build: ./gateway
    image: "gateway:latest"